name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
        django-version: [
          "Django>=3.2,<3.3",
          "Django>=4.0,<4.1",
        ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install "${{ matrix.django-version }}"
        python -m pip install .
        python -m pip install -r requirements_test.txt
    - name: Run Tests
      run: |
        py.test --cov=service_status
